---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      update_cache: yes
  
  - name: install apache2 and php package
    tags: apache.apache2.ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      

  
